### ISSUE TITLE
Can you make a function that when click use the device on wifi privacy,it will use the real device Mac address rather than the customized Mac address

### ISSUE THREAD

**Issue by havfu** [DavidBerdik/MACsposed#13]
Can you make a in-app function that when click use the device on wifi privacy,it will use the real device Mac address rather than the customized Mac address

**Comment by DavidBerdik** [comment]
Yes, once the MACsposed UI is designed, I want to add this. I cannot currently provide a timeline for when it will be finished, though.

**Comment by DavidBerdik** [comment]
The ability to set MACsposed to use the device's real MAC address when the override is enabled was added with the release of MACsposed v1.2.0, so I am going to close this now. I hope you have a chance to try it out!
