### ISSUE TITLE
The first screen of the card cannot be started.

### ISSUE THREAD

**Issue by lsdlh** [DavidBerdik/MACsposed#15]
MACsposed v1.2.0 miui android14 ，Use kernelsu authorization，The first screen of the card cannot be started

**Comment by DavidBerdik** [comment]
Do I understand correctly that you are saying that you are stuck on this screen even after granting root access? If yes, then please try either rebooting your phone or force stopping MACsposed and reopening it. I probably should have made that clearer in the message text. I can change it in the next release.

![Screenshot_20240731-133027_MACsposed](https://github.com/user-attachments/assets/8d5be227-5a48-447b-bf10-6dacf5e053c7)

**Comment by lsdlh** [comment]
> Do I understand correctly that you are saying that you are stuck on this screen even after granting root access? If yes, then please try either rebooting your phone or force stopping MACsposed和reopening it. I probably should have made that clearer in the message text. I can change it in the next release.
> 
> ![Screenshot_20240731-133027_MACsposed](https://private-user-images.githubusercontent.com/7663225/353928538-8d5be227-5a48-447b-bf10-6dacf5e053c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MTg3NDksIm5iZiI6MTcyMjYxODQ0OSwicGF0aCI6Ii83NjYzMjI1LzM1MzkyODUzOC04ZDViZTIyNy01YTQ4LTQ0N2ItYmYxMC02ZGFjZjVlMDUzYzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMTcwNzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGRkZGU4OGUwY2MwM2FhMTIyZDFiZDNmM2M0MjY5MDE4ODhmNDg1YWZiMzNiZWY5NmE2YjMwNjNlMDFiMjAwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MnrOoBgp1MVtimYHp2sufiolCcd6kGJPwe2F-nQaycU)

After the software is granted root, manually restart the phone, the phone cannot be turned on, and it is stuck in the first screen animation.

**Comment by DavidBerdik** [comment]
> After the software is granted root, manually restart the phone, the phone cannot be turned on, and it is stuck in the first screen animation.

Does the issue persist when you uninstall MACsposed?

**Comment by GurumiHeist** [comment]
> > After the software is granted root, manually restart the phone, the phone cannot be turned on, and it is stuck in the first screen animation.
> 
> Does the issue persist when you uninstall MACsposed?

I've experienced the same issue.... I'm using Redmi Not 11 Pro+ 5G (Peux), tried on Android 13 & Android 14 HyperOS but once root access is granted and module is enabled in LSPosed, it asks for reboot and gets the device stuck on bootloop.

**Comment by DavidBerdik** [comment]
Ugh. This is the problem with building these types of applications. Unless you have many different phones, it's impossible to do proper testing to make sure that what works on one phone does not break on another.

@GurumiHeist Which version of LSPosed are you using?

**Comment by DavidBerdik** [comment]
@GurumiHeist Are you using KernelSU?

**Comment by DavidBerdik** [comment]
After further research, I have identified what's going on here.

I am going to use #16 to track this. Please follow it for updates on progress.

**Comment by lsdlh** [comment]
> > After the software is granted root, manually restart the phone, the phone cannot be turned on,和it is stuck in the first screen animation.
> 
> Does the issue persist when you uninstall MACsposed?

LSPose1.9.3,It still can't start after uninstalling the app.，To delete the files generated by MACsposed in the/data/adb/modules/folder

**Comment by DavidBerdik** [comment]
> LSPose1.9.3,It still can't start after uninstalling the app.，To delete the files generated by MACsposed in the/data/adb/modules/folder

Thank you for the information. I am really sorry for the inconvenience this has caused. I am tracking the issue you are facing in issue #16 and hope to have a fix very soon.
