### ISSUE TITLE
MACsposed 1.2.0 causes bootloop with KernelSU

### ISSUE THREAD

**Issue by DavidBerdik** [DavidBerdik/MACsposed#16]
There is a known issue with MACsposed 1.2.0 that causes a bootloop on devices that are rooted with KernelSU. I am actively working to resolve the issue as well as investigating how this extremely serious flaw managed to slip through my testing process. 

**If you are a KernelSU user, do not update to MACsposed 1.2.0. Please wait for MACsposed 1.2.1.**

**Comment by lsdlh** [comment]
MACsposed v1.2.0 miui android14 ，Use kernelsu authorization，LSPose1.9.3,It cannot be turned on after restart, and the animation will be started on the first screen of the card，It still can't start after uninstalling the app.，To delete the files generated by MACsposed in the/data/adb/modules/folder

**Comment by DavidBerdik** [comment]
@lsdlh If I gave you a test build, would you be willing to try it out for me and tell me if it works?

**Comment by GurumiHeist** [comment]
Tried on 
KernelSU version: 11872
Android 13 & Android 14
LSPosed-v1.9.2 & LSPosed-v1.9.3_mod

**Comment by DavidBerdik** [comment]
@GurumiHeist Would you be willing to try out a test build and tell me if it fixes the problem?

**Comment by GurumiHeist** [comment]
> @GurumiHeist Would you be willing to try out a test build and tell me if it fixes the problem?

Sure

**Comment by DavidBerdik** [comment]
@GurumiHeist Thanks! Here's a copy of what I am tentatively planning to release as MACsposed 1.2.1. Please try it and let me know if it works. GitHub does not allow APKs to be uploaded to comments, so it is contained inside a zip.

[MACsposed-1.2.1.zip](https://github.com/user-attachments/files/16484697/MACsposed-1.2.1.zip)

**Comment by GurumiHeist** [comment]
> @GurumiHeist Thanks! Here's a copy of what I am tentatively planning to release as MACsposed 1.2.1. Please try it and let me know if it works. GitHub does not allow APKs to be uploaded to comments, so it is contained inside a zip.
> 
> [MACsposed-1.2.1.zip](https://github.com/user-attachments/files/16484697/MACsposed-1.2.1.zip)

Oh damn. No boot loop this time but uh....
![Screenshot_20240804-061548_MACsposed](https://github.com/user-attachments/assets/75a2f92a-b2f4-4e32-ab1f-90779f0d5d3e)

**Comment by DavidBerdik** [comment]
@GurumiHeist Excellent! Since this issue is now resolved and the new release has launched, I am going to close this issue and unpin it.

Regarding the new license requirement for MACsposed, I can totally understand why you and many other users will not be happy about it. I am not particularly happy about it either, but unfortunately, I simply cannot continue to provide MACsposed for free while also maintaining a high standard of quality for it. I thought long and hard about this and it was not a decision that I made lightly.

That said, since the information you shared with me was extremely important for resolving the boot issue, I would like to offer you a 50% refund on a purchase of a lifetime license. If you are interested, please contact me privately with your order number after purchasing and I will issue the partial refund.
