### ISSUE TITLE
Why the paid subscription?

### ISSUE THREAD

**Issue by ekko95** [DavidBerdik/MACsposed#19]
I'm honestly confused by it? Why not just like a one time payment or something?

**Comment by DavidBerdik** [comment]
If you do not want to pay for MACsposed on a subscription basis, then there is an option to purchase a lifetime license as well. Some users prefer subscriptions over lifetime purchases, and so, I have made that option available. I saw that you left a one-star review on the Play Store stating that this is sad, but giving users freedom of choice over how they want to pay is not sad. 🙂

Here is a screenshot showing the user interface of the payment prompt.

![image](https://github.com/user-attachments/assets/df00aba8-ac7c-42c3-92bb-d69e143dfe16)
