### ISSUE TITLE
Add support for Oneplus Android 11

### ISSUE THREAD

**Issue by Elegary** [DavidBerdik/MACsposed#4]
Hello,

Since OnePlus has the same process to randomise mac address but on Android 11, is it possible to add support for this version ?

Thanks by advance

**Comment by DavidBerdik** [comment]
Hello,

As I am sure you already know, OnePlus uses a fork of Android called OxygenOS on their devices. Unfortunately, this fork is not completely open source (only the kernels are), and therefore, I can't really look into the operating system's functionality to determine how to support it. I also do not own any OnePlus devices on which I could do testing or experimentation to figure out how to support it despite the lack of access to the source code. I wish I could help you, but as far as I can tell, I'm pretty sure there's nothing I can do unless I acquire a OnePlus phone that runs Android 11.

**Comment by Elegary** [comment]
I totally understand the problem.

 I have my OnePlus on Android 11. I will try to use JADX to decompile and look at the code. If I got something, I will try to write this new feature myself and send you my result.

**Comment by DavidBerdik** [comment]
Good luck with your research! I hope you manage to pull it off, and of course, I look forward to seeing the result of the work!

**Comment by DavidBerdik** [comment]
Since there is unfortunately nothing I can do to help with this ticket, I am going to label it as `wontfix` and mark it as closed.

@Elegary If you wish to follow up this discussion at some point with additional information about how your development is coming along, please feel free to leave a reply here.

**Comment by Elegary** [comment]
> Since there is unfortunately nothing I can do to help with this ticket, I am going to label it as `wontfix` and mark it as closed.
> 
> @Elegary If you wish to follow up this discussion at some point with additional information about how your development is coming along, please feel free to leave a reply here.

Yes you can close this ticket. I don't have a lot of time currently, I'm busy with professional and personal imperatives, but it's on my (looong) Todo list!

**Comment by DavidBerdik** [comment]
Totally understandable and relatable. I hope you have time to revisit this someday!
