### ISSUE TITLE
Can you integrate the functionality to modify the MAC address?

### ISSUE THREAD

**Issue by plus1998** [DavidBerdik/MACsposed#5]
All in one.

**Comment by DavidBerdik** [comment]
Hello! This request is actually something that I have been wanting to add to MACsposed for quite a while, but I haven't had the time to do so. If you or anyone else who sees this would like to add this feature and submit a pull request for it, that would be greatly appreciated! If not, I will get around to doing it eventually, but I cannot provide a concrete timeline for when it will be done.
