### ISSUE TITLE
Best App to Change Wifi Mac with MACsposed

### ISSUE THREAD

**Issue by NivinCNC** [DavidBerdik/MACsposed#6]
Hi.. I am Using Poco M2 with Pixel experience extended Custom Rom..I have been trying to change my mac with - change my mac app With MACsposed 
installed but it didnt help me...Finally after lot of trys I found another app Wifi Mac changer ( https://play.google.com/store/apps/details?id=com.wireless.macchanger ) which worked perfectly with MACsposed installed.....just need to grant root permission, enter the mac that we want and click "Hard change" (simple change doest work) with MACsposed enabled on tile. It worked fine on my poco and redmi phones...... Suggesting this app may help people who are struggling to change mac on change my mac app which now doest work on most phones...

**Comment by DavidBerdik** [comment]
Thank you for making me aware of this! One thing that is difficult about suggesting an app to use for changing your MAC address is that not all apps work on all phones. For example, I use [this app](https://play.google.com/store/apps/details?id=com.wireless.macchanger) on my Pixel 6 Pro, but it does not work on my Pixel 3 XL, so I use [this app](https://play.google.com/store/apps/details?id=net.xnano.android.changemymac) instead.

Ultimately what I want to do is eliminate the need for use of a third party app as described in #5, however, creating a list as people report working apps along the way would be a decent interim solution.

**Comment by NivinCNC** [comment]
Thats Fine...Then Making an app with all possible methods to change the MAC adrdress will be an ultimate Solution for this.
